spring:
  application:
    name: order-service-gateway
  webflux:
    base-path: /${spring.application.name}

audit:
  enabled: true
  topic:
    request: order-service-request-log
    response: order-service-response-log
  kafka:
    bootstrap-address: 127.0.0.1:9092

rest:
  client:
    order-service:
      host: http://localhost:8080
      uris:
        create: /order-service/order
        get: /order-service/order/{ordId}
      readTimeout: 60s
      connectionTimeout: 10s

test:
  payload:
    generator:
      enabled: false

server:
  port: 8081
