spring:
  application:
    name: order-service-gateway
  webflux:
    base-path: /${spring.application.name}

kafka:
  bootstrap-address: 127.0.0.1:9092

audit:
  topic:
    order-service-log

rest:
  client:
    order-service:
      host: http://localhost:8080
      uri: /order-service/order
      readTimeout: 60s
      connectionTimeout: 10s

server:
  port: 8081
